extent.reporter.spark.start=true
extent.reporter.spark.out=target/ExtentSparkReports/reports.html

extent.reporter.pdf.start=true
extent.reorter.pdf.out=target/ExtentPdfReports/reports.pdf

extent.reporter.html.start=true
extent.reporter.html.out=target/ExtentHtmlReports/reports.html

basefolder.name=target/ExtentReports/
basefolder.datetimepattern=dd-MMM-yyyy HH mm ss

        systeminfo.user= Yogesh Kulkarni
		systeminfo.os=Window 11 OS
		systeminfo.build= Release 11 and sprint 1
		systeminfo.AppName= SIT Environment Cogmento CRM application
